//
//  PokemonsListViewController.swift
//  Pokedex
//
//  Created Alexis Schultz on 03/08/2017.
//  Copyright © 2017 Alexis Schultz. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Whisper
import SwifterSwift

class PokemonsListViewController: UIViewController, PokemonsListViewProtocol
{
	var presenter: PokemonsListPresenterProtocol?
    var refreshControl: UIRefreshControl! = UIRefreshControl()
    var pokemons : [(String, String)] = []

    @IBOutlet weak var pokemonsTableView: UITableView!
    {
        didSet
        {
            pokemonsTableView.register(UINib(nibName: "PokemonCell", bundle: Bundle.main), forCellReuseIdentifier: "PokemonCell")
            pokemonsTableView.register(UINib(nibName: "LoadMoreCell", bundle: Bundle.main), forCellReuseIdentifier: "LoadMoreCell")
            pokemonsTableView.rowHeight = UITableViewAutomaticDimension
            pokemonsTableView.estimatedRowHeight = 50
            pokemonsTableView.tableFooterView = UIView()
        }
    }
    
	override func viewDidLoad()
    {
        super.viewDidLoad()
        refreshControl.attributedTitle = NSAttributedString(string:"Refresh")
        refreshControl.addTarget(self, action: #selector(PokemonsListViewController.didRequestRefresh), for: UIControlEvents.valueChanged)
        pokemonsTableView.refreshControl = refreshControl
        presenter?.loadInitialData()
    }

    override func viewDidAppear(_ animated: Bool)
    {
        tabBarController?.navigationItem.title = "Pokedex"
    }

    func didRequestRefresh()
    {
        presenter?.loadInitialData()
    }

    func didRequestLoadMore()
    {
        presenter?.loadMoreData()
    }

    func reloadData(pokemons : [(String, String)], isInitialLoad : Bool)
    {
        if isInitialLoad
        {
            self.pokemons.removeAll()
        }
        self.pokemons.append(contentsOf: pokemons)
        pokemonsTableView.reloadData()
        refreshControl.endRefreshing()
    }

    func didFailedToLoadData(errorMessage : String, isInitialLoad: Bool)
    {
        defer
        {
            var murmur = Murmur(title: errorMessage)
            murmur.backgroundColor = .red
            murmur.titleColor = .white
            Whisper.show(whistle: murmur, action: .show(2))
        }
        if !isInitialLoad
        {
            guard let lastIdexPath = pokemonsTableView.indexPathForLastRow, let cell = pokemonsTableView.cellForRow(at: lastIdexPath) as? LoadMoreCell else
            {
                return
            }
            cell.activityIndicatorView.stopAnimating()
        }
        else
        {
            refreshControl.endRefreshing()
        }
    }
}

// MARK: - UITableViewDataSource
extension PokemonsListViewController: UITableViewDataSource
{
    func numberOfSections(in tableView: UITableView) -> Int
    {
        return 1
    }

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
    {
        guard section == 0 else { return 0 }
        guard let presenter = presenter else { return 0 }
        return presenter.shouldShowLoadMoreCell() ? pokemons.count + 1 : pokemons.count
    }

    func tableView(_ tableView : UITableView, cellForRowAt indexPath : IndexPath) -> UITableViewCell
    {
        guard indexPath.section == 0 else { fatalError("PokemonsListViewController : bad section") }
        if indexPath.row == pokemons.count
        {
            guard let cell = tableView.dequeueReusableCell(withIdentifier: "LoadMoreCell", for: indexPath) as? LoadMoreCell else
            {
                fatalError("PokemonsListViewController : can't initialize cell with identifier : LoadMoreCell")
            }
            cell.activityIndicatorView.startAnimating()
            cell.retryCallback = self.didRequestLoadMore
            return cell
        }
        else
        {
            guard let cell = tableView.dequeueReusableCell(withIdentifier: "PokemonCell", for: indexPath) as? PokemonCell else
            {
                fatalError("PokemonsListViewController : can't initialize cell with identifier : PokemonCell")
            }
            cell.pokemonName = pokemons[indexPath.row].0
            cell.pokemonUrl = pokemons[indexPath.row].1
            cell.contentView.setNeedsLayout()
            cell.contentView.layoutIfNeeded()
            return cell
        }
    }
}

// MARK: - UITableViewDelegate
extension PokemonsListViewController : UITableViewDelegate
{
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath)
    {
        if cell is LoadMoreCell
        {
            didRequestLoadMore()
        }
    }

    func tableView(_ tableView: UITableView, shouldHighlightRowAt indexPath: IndexPath) -> Bool
    {
        guard let pokemonCell = self.pokemonsTableView.cellForRow(at: indexPath) as? PokemonCell, let name = pokemonCell.pokemonName, let url = pokemonCell.pokemonUrl else { return false }
        presenter?.didSelectPokemon(name: name, url: url)
        return false
    }

    /*func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]?
    {
        guard indexPath.section == 0 else
        {
            return nil
        }
        let share = UITableViewRowAction(style: .normal, title: "Save") { (action, indexPath) in
            if let pokemonCell = self.pokemonsTableView.cellForRow(at: indexPath) as? PokemonCell, let pokemon = pokemonCell.pokemon, let name = pokemon.name
            {
                self.presenter?.save(pokemonId: pokemon.id, pokemonName: name)
            }
        }
        share.backgroundColor = UIColor.blue
        return [share]
    }*/
}
