//
//  PokemonDetailsPresenter.swift
//  Pokedex
//
//  Created Alexis Schultz on 03/08/2017.
//  Copyright © 2017 Alexis Schultz. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PokemonDetailsPresenter: PokemonDetailsPresenterProtocol, PokemonDetailsInteractorOutputProtocol {



    weak private var view: PokemonDetailsViewProtocol?
    var interactor: PokemonDetailsInteractorInputProtocol?
    private let router: PokemonDetailsWireframeProtocol

    var pokemonUrl : String?
    {
        didSet
        {
            guard let url = pokemonUrl else { return }
            interactor?.loadPokemonDetails(from : url)
        }
    }

    var pokemon : Pokemon?
    {
        didSet
        {
            guard let pokemon = pokemon else { return }
            view?.update(pokemon: pokemon)
        }
    }
    
    init(interface: PokemonDetailsViewProtocol, interactor: PokemonDetailsInteractorInputProtocol?, router: PokemonDetailsWireframeProtocol)
    {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func didLoad(pokemon: Pokemon)
    {
        self.pokemon = pokemon
    }
}
