//
//  SavedPokemonsListRouter.swift
//  Pokedex
//
//  Created Alexis Schultz on 03/08/2017.
//  Copyright © 2017 Alexis Schultz. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SavedPokemonsListRouter: SavedPokemonsListWireframeProtocol
{

    weak var viewController: UIViewController?

    static func loadModule() -> UIViewController
    {
        // Change to get view from storyboard if not using progammatic UI
        let view = SavedPokemonsListViewController(nibName: nil, bundle: nil)
        let interactor = SavedPokemonsListInteractor()
        let router = SavedPokemonsListRouter()
        let presenter = SavedPokemonsListPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        let savedPokemonListTabBarItem = UITabBarItem(title: "Saved Pokemons", image: UIImage(named: "heartLight"), selectedImage: UIImage(named: "heartBold"))
        view.tabBarItem = savedPokemonListTabBarItem
        return view
    }
}
