//
//  SavedPokemonsListProtocols.swift
//  Pokedex
//
//  Created Alexis Schultz on 03/08/2017.
//  Copyright © 2017 Alexis Schultz. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RealmSwift

//MARK: Wireframe -
protocol SavedPokemonsListWireframeProtocol: class {

}
//MARK: Presenter -
protocol SavedPokemonsListPresenterProtocol: class {

    var interactor: SavedPokemonsListInteractorInputProtocol? { get set }
    func getSavedPokemons() -> Results<Pokemon>?
}

//MARK: Interactor -
protocol SavedPokemonsListInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SavedPokemonsListInteractorInputProtocol: class {

    var presenter: SavedPokemonsListInteractorOutputProtocol?  { get set }
    func getSavedPokemons() -> Results<Pokemon>
    /* Presenter -> Interactor */
}

//MARK: View -
protocol SavedPokemonsListViewProtocol: class {

    var presenter: SavedPokemonsListPresenterProtocol?  { get set }
    /* Presenter -> ViewController */
}
