//
//  SavedPokemonsListPresenter.swift
//  Pokedex
//
//  Created Alexis Schultz on 03/08/2017.
//  Copyright © 2017 Alexis Schultz. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RealmSwift

class SavedPokemonsListPresenter: SavedPokemonsListPresenterProtocol, SavedPokemonsListInteractorOutputProtocol {

    weak private var view: SavedPokemonsListViewProtocol?
    var interactor: SavedPokemonsListInteractorInputProtocol?
    private let router: SavedPokemonsListWireframeProtocol

    init(interface: SavedPokemonsListViewProtocol, interactor: SavedPokemonsListInteractorInputProtocol?, router: SavedPokemonsListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getSavedPokemons() -> Results<Pokemon>? {
        return interactor?.getSavedPokemons()  // todo change that
    }
}
